### ISSUE TITLE
Preprocessing: add_fields_with_value broken

### ISSUE THREAD

**Issue by sholtkamp** [nPhil01/EagleOwlsGenderDifference#2]
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/Basti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\data_preprocessing.py", line 108, in add_fields_to_shapefile
    self.add_fields_with_value("deploy_on", 2, 1)
  File "C:/Users/Basti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\data_preprocessing.py", line 64, in add_fields_with_value
    self.layerCopy.updateFields()
NameError: name 'QVariant' is not defined

Could not find fix for QVariant not defined error

**Comment by vgorte** [comment]
Hast du mal probiert `from PyQt4.QtCore import QVariant` in die data_preprocessing.py zu schreiben? Bin grade nicht an einem rechner um es zu testen.

Siehe: https://stackoverflow.com/questions/9257422/how-to-get-the-original-python-data-from-qvariant

**Comment by sholtkamp** [comment]
Ja und auch yQt5.QtCore und ohne Version (nimmt dann die aktuellste)
